apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: roboshop
  labels:
    component: mongodb 
    env: dev
    project: roboshop
spec:
  ports:
    - protocol: TCP 
      port: 27017   
      targetPort: 27017
  clusterIP: None
  selector:
    component: mongodb 
    env: dev
    project: roboshop